# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbb7f9da06f39c1f0ed7855d63a9493a4f4fed765acfc189fb0b639cd69afe181e9b03682a7cb39467da94f1efb0856389114270b048fa81d064c1d67b50ec2a

test:
  secret_key_base: 1e35a51d8b0c74eadc1325bc6419137af8bfc20fdb0d7886d18f913c6895223df7ece70fb467d3309dc595fb517fd4f15f9abd7f9f968fb7f748911f97b17e00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
